const initialProducts = [
    {
        id: 1,
        title: "Wall Panel Revestimiento De Pared Eps Interior X4 Marrón",
        description: "Pack de 4 tablas EPS (290x12x1,2 cm) que cubren 1,28 m².",
        price: 55000,
        code: "025690",
        thumbnail: "product01.jpg",
        stock: 10,
    },
    {
        id: 2,
        title: "Revestimiento De Pared Interior Wall Panel Eps Beige",
        description: "Tabla individual EPS (290x12x1,2 cm), cubre 0,32 m².",
        price: 13000,
        code: "025691",
        thumbnail: "product02.jpg",
        stock: 15,
    },
    {
        id: 3,
        title: "Revestimiento De Pared Interior Wall Panel Eps Marron Oscuro",
        description: "Tabla individual EPS (290x12x1,2 cm), cubre 0,32 m².",
        price: 13000,
        code: "025692",
        thumbnail: "product03.jpg",
        stock: 12,
    },
    {
        id: 4,
        title: "Revestimiento De Pared Interior Wall Panel Eps Negro",
        description: "Tabla individual EPS (290x12x1,2 cm), cubre 0,32 m².",
        price: 13000,
        code: "025695",
        thumbnail: "product04.jpg",
        stock: 8,
    },
    {
        id: 5,
        title: "Revestimiento Wall Panel Pared Varillado Madera Pvc Wpc Negro",
        description: "Revestimiento vertical WPC, 280x16x2,4 cm, cubre 0,45 m².",
        price: 15000,
        code: "025696",
        thumbnail: "product05.jpg",
        stock: 20,
    },
    {
        id: 6,
        title: "Revestimiento Pared Wall Panel Wpc Madera Gris Oscuro",
        description: "WPC (290x15 cm). Imitación madera natural, resistente.",
        price: 13500,
        code: "025697",
        thumbnail: "product06.jpg",
        stock: 18,
    },
    {
        id: 7,
        title: "Revestimiento Pared Wall Panel Wpc Madera Marron Castañas",
        description: "WPC (290x15 cm). Textura cálida y duradera.",
        price: 13500,
        code: "025698",
        thumbnail: "product07.jpg",
        stock: 14,
    },
    {
        id: 8,
        title: "Panel Varillado Revestimiento De Pared Eps Natural Teka",
        description: "EPS símil madera, 250x11 cm. Fácil instalación.",
        price: 11000,
        code: "025699",
        thumbnail: "product08.jpg",
        stock: 25,
    },
    {
        id: 9,
        title: "Wall Panel Eps Dela Revestimiento De Pared Interior Gris",
        description: "Modelo Dela (285x16x1,2 cm). Antideslizante, antibacterial.",
        price: 13656,
        code: "025305",
        thumbnail: "product09.jpg",
        stock: 10,
    },
    {
        id: 10,
        title: "Wall Panel Revestimiento Pared Varillado Interior Símil Dela",
        description: "Modelo Grafito (285x16x1,2 cm). Símil madera.",
        price: 13600,
        code: "027345",
        thumbnail: "product10.jpg",
        stock: 10,
    },
    {
        id: 11,
        title: "Wall Panel Revestimiento Eps De Pared Interior Símil Stena",
        description: "Modelo Champagne (285x12x2,1 cm). Fácil limpieza.",
        price: 15200,
        code: "033345",
        thumbnail: "product11.jpg",
        stock: 9,
    },
    {
        id: 12,
        title: "Revestimiento Wall Panel Pared Eps Interior Murus X Unidad",
        description: "Modelo Murus (285x12x1,2 cm). Símil madera.",
        price: 13124,
        code: "076545",
        thumbnail: "product12.jpg",
        stock: 11,
    },
    {
        id: 13,
        title: "Revestimiento De Pared Wall Panel Wpc Simil Madera Interior",
        description: "Modelo Y150 (290x15,5x1,5 cm). Resistente a humedad.",
        price: 33098,
        code: "045789",
        thumbnail: "product13.jpg",
        stock: 7,
    },
    {
        id: 14,
        title: "Wall Panel PVC Símil Madera Blanco",
        description: "Panel PVC blanco mate (300x20 cm). Fácil de limpiar.",
        price: 14500,
        code: "025700",
        thumbnail: "product14.jpg",
        stock: 12,
    },
    {
        id: 15,
        title: "Wall Panel EPS Varillado Gris Cemento",
        description: "EPS gris cemento (285x15 cm). Aislante y antibacterial.",
        price: 12900,
        code: "025701",
        thumbnail: "product15.jpg",
        stock: 8,
    },
    {
        id: 16,
        title: "Revestimiento EPS Varillado Nogal Oscuro",
        description: "EPS nogal oscuro (280x12 cm). Estilo elegante.",
        price: 13900,
        code: "025702",
        thumbnail: "product16.jpg",
        stock: 16,
    },
    {
        id: 17,
        title: "Wall Panel PVC Acabado Mate Negro",
        description: "PVC negro mate (290x15 cm). Diseño moderno.",
        price: 15500,
        code: "025703",
        thumbnail: "product17.jpg",
        stock: 14,
    },
    {
        id: 18,
        title: "Revestimiento WPC Marrón Avellana",
        description: "WPC marrón avellana (290x15 cm). Resistente al agua.",
        price: 14800,
        code: "025704",
        thumbnail: "product18.jpg",
        stock: 9,
    },
    {
        id: 19,
        title: "Revestimiento EPS Blanco Nevado",
        description: "EPS blanco nevado (300x20 cm). Luminoso y fácil instalación.",
        price: 12500,
        code: "025705",
        thumbnail: "product19.jpg",
        stock: 20,
    },
    {
        id: 20,
        title: "Panel EPS Grafito Oscuro Interior",
        description: "EPS grafito oscuro (285x16 cm). Ideal para oficinas.",
        price: 14200,
        code: "025706",
        thumbnail: "product20.jpg",
        stock: 10,
    },
];

export default initialProducts;